movie_project/authentication/urls.py
from . import views
from django.urls import path
app_name='authentication'

urlpatterns = [
path('reg',views.reg,name='reg'),
path('login',views.login,name='login'),
path('logout',views.logout,name='logout'),


]

movie_project/movie_app/urls.py
from django.urls import path
from . import views

app_name = 'movie_app'

urlpatterns = [
    path('', views.allProdCat, name='allProdCat'),
    path('<slug:c_slug>/<int:id>/', views.allProdCat, name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/', views.proDetail, name='prodCatdetail'),
    path('add_product/', views.add_product, name='add_product'),
    path('/edit_product/<int:id>/', views.edit_product, name='edit_product'),
    path('/delete_product/<int:id>/', views.delete_product, name='delete_product'),
    path('/product/<int:product_id>/add_comment/', views.add_comment, name='add_comment'),
    path('/product/<int:product_id>/add_rating/', views.add_rating, name='add_rating'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),

    
  
]

movie_project/movie_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movie_app.urls')),
    path('authentication/', include('authentication.urls', namespace='authentication')),
    path('search/', include('search_app.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

movie_project/search_app/urls.py
from django.urls import path
from . import views

app_name='search_app'
urlpatterns=[
    path('',views.SearchResult,name='SearchResult'),

]

movie_project/movie_app/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model




class User(models.Model):
    username=models.CharField(max_length=255)
    first_name=models.CharField(max_length=255)
    last_name=models.CharField(max_length=255)
    email=models.EmailField(unique=True)
    password=models.CharField(max_length=255)

    def __str__(self):
        return '{}'.format(self.username)

class category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    image=models.ImageField(upload_to='category',blank=True)

    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'
    def get_url(self):
        return reverse('movie_app:products_by_category', args=[self.slug, self.id])

    def __str__(self):
        return '{}'.format(self.name)
class products(models.Model):
    name=models.CharField(max_length=250)
    slug=models.SlugField(max_length=250,unique=True)
    poster=models.ImageField(upload_to='poster')
    description=models.TextField()
    release_date=models.DateField()
    actors=models.CharField(max_length=255)
    category_id=models.ForeignKey(category,on_delete=models.CASCADE)
    trailer_link=models.URLField()
    user=models.ForeignKey(get_user_model(),on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)

        if not isinstance(self.user, get_user_model()):
            # Fetch the user instance based on the provided user information
            self.user = get_user_model().objects.get(username=self.user.username)

        super().save(*args, **kwargs)

    def get_url(self):
        return reverse('movie_app:prodCatdetail',args=[self.category_id.slug,self.slug])

    class Meta:
        ordering=('name',)
        verbose_name='product'
        verbose_name_plural='products'


    def __str__(self):
        return '{}'.format(self.name)

    def average_rating(self):
        ratings = Rating.objects.filter(product=self)
        if ratings.exists():
            return sum(rating.rating for rating in ratings) / ratings.count()
        return 0

    def total_ratings(self):
        return Rating.objects.filter(product=self).count()


    
class Comment(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    product = models.ForeignKey(products, on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

class Rating(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    product = models.ForeignKey(products, on_delete=models.CASCADE)
    rating = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f"{self.user.username} - {self.product.name} - {self.rating}"

movie_project/templates/add_comment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Comment</title>
    <style>
        body {
            background-color: #ffffff; /* Dark black background */
            color: #DE3163; /* Text color */
        }

        h2 {
            color: #DE3163; /* Heading color */
        }

        form {
            border: 2px solid  #e60a0a; /* Light black field box */
            padding: 20px;
            margin: 20px;
            border-radius: 10px;
        }

        input, textarea {
            color: #020202; /* Input text color */
            border: 2px solid  #e60a0a;
            
            padding: 10px;
            margin-bottom: 10px;
            border-radius: 5px;
        }

        button {
            background-color: #fc0000; /* Button color */
            color: #fff; /* Button text color */
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }

        button:hover {
            background-color: #bf2121; /* Darker shade on hover */
        }

    </style>
</head>
<body>
    <form method="post" action="{% url 'movie_app:add_comment' product_id=product.id %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit Comment</button>
    </form>
</body>
</html>

movie_project/templates/add_product.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Product</title>
    <style>
        body {
            background-color: #ffffff; /* Dark black background */
            color: #ff0000; /* Text color */
        }

        h2 {
            color: #ff0000; /* Heading color */
        }

        form {
           border: 2px solid #f80000;/* Light black field box */
            padding: 20px;
            margin: 20px;
            
        }

        input {
            border: 2px solid #f80000;/* Input text color */
        }

        button {
            background-color: #ff0000; /* Button color */
            color: #fff; /* Button text color */
            padding: 10px 20px;
            border: none;
            border-radius: 6px;
            cursor: pointer;
        }

        button:hover {
            background-color: #c72626; /* Darker shade on hover */
        }
        input,textarea{
            border: 2px solid #f80000;

    }
    </style>
</head>
<body>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Add Product</button>
    </form>
</body>
</html>

movie_project/templates/add_rating.html
{% extends 'base.html' %}

{% block content %}
  
  <form method="post" style="max-width: 400px; margin: 0 auto; margin-top: 20px;">
    {% csrf_token %}
    <div style="margin-bottom: 15px;">
      <label for="id_rating" style="display: block; color: #FF5733; font-weight: bold;">Rating:</label>
      {{ form.rating }}
    </div>
  
    <button type="submit" style="background-color: #FF5733; color: #fff; padding: 10px 20px; border: none; border-radius: 5px; cursor: pointer;">Submit Rating</button>
  </form>
{% endblock %}

movie_project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/custome.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/fc51e437b8.js"></script>
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Marvel:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">

  <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div>
{% include 'navbar.html' %}
{% block content %}
{% endblock %}
</div>
{% include 'footer.html' %}
<script src="https://kit.fontawesome.com/7530bf5d2d.js" crossorigin="anonymous"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

movie_project/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
   {% if category %}
      {{ category.description|truncatewords:155 }}
   {% else %}
       welcome to store where you can experience different tastes....
   {% endif %}
{% endblock %}
{% block title %}
    {% if category %}
        {{ category.name }} -  Borcelle
    {% else %}
         see our new collections - Borcelle
    {% endif %}
{% endblock %}

{% block content %}
    {% if category %}
      <div>
        <div class="row my_row_class">
            <div class="mx-auto">
            <p class="text-center custom_a" ><a href="{% url 'movie_app:allProdCat' %}" class="custom_a" style="font-variant-caps: all-petite-caps; font-weight:600; text-decoration: none; color: rgb(10, 10, 10);">show all <i class="fa-solid fa-reply-all"></i></a> </p>
        </div>
            </div>
      </div>
    {% endif %}
      <div class="mx_auto">
    {% if category %}
            
      </div>
      <br>
      <div style="font-variant-caps: all-petite-caps; font-weight:600;">
             <h1 class="text-center my_title"><b>{{category.name}}</b></h1>
             <p class="text-center">{{category.description}}</p>
      </div>
    {% else %}
    <div class="text-center">
      <img src="{% static 'image/endgame.jpg' %}" style="max-width: 100%; height: 200%; ">
  </div>
  

      </div>
      <br>
    {% endif %}
    <div class="container mt-5" style="margin-bottom: 100px;">
      <div class="row mx-auto">
          {% for product in products %}
          <div class="my_bottom_margin col-12 col-sm-6 col-md-4 col-lg-3">
              <div class="card text-center" style="width: 250px; height: 350px; margin-right: 40px; margin-top: 20px;">
                  <a href="{{ product.get_url }}" class="image-link">
                      <img class="card-img-top my_image" src="{{ product.poster.url }}" alt="{{ product.name }}">
                  </a>
              </div>
          </div>
          {% endfor %}
      </div>
  </div>
  
  <style>
      .image-link:hover img {
          transform: scale(1.2); /* Scales the image to 120% of its original size */
          transition: transform 0.6s ease; /* Smooth transition for the scaling effect */
      }
  
      .my_bottom_margin {
          margin-bottom: 20px; /* Adjust the spacing between rows of cards as needed */
      }
  </style>
  
  
      </div>
{% endblock %}

movie_project/templates/delete_product.html
{% extends 'base.html' %}

{% block content %}

  <p style="color: #DE3163; margin-top: 20px;">Are you sure you want to delete the product '{{ product.name }}'? This action cannot be undone.</p>

  <form method="post" style="margin-top: 20px;">
    {% csrf_token %}
    <button type="submit" style="background-color: #ff0000; color: #fff; padding: 10px 20px; border: none; border-radius: 5px; cursor: pointer;">Yes, Delete</button>
    <a href="{% url 'movie_app:allProdCat' %}" style="color: #ff0000; margin-left: 10px; text-decoration: none;">Cancel</a>

  </form>

  <style>
    body {
        background-color: #ffffff; /* Dark black background */
        color: #DE3163; /* Text color */
    }

    .my_title {
        color: #DE3163; /* Heading color */
    }
    input,textarea{
    background-color: #333;

    }
  </style>
  
{% endblock %}

movie_project/templates/edit_product.html
{% extends 'base.html' %}

{% block content %}
  <form method="post" enctype="multipart/form-data" style="margin-bottom: 100px; padding: 20px; background-color: #fcfcfc; border: 2px solid  #e60a0a;">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" style="background-color:#e60a0a; color: #fff; padding: 10px 20px; border: none; cursor: pointer;">Save Changes</button>

  </form>

  <style>
    body {
        background-color: #ffffff; /* Dark black background */
        color: #ff0000; /* Text color */
    }

    .my_title {
        color: #000000; /* Heading color */
    }

    form {
        margin-top: 20px;
    }
     input,textarea{
    background-color: #ffffff;
    border: 2px solid  #e60a0a;

    }
  </style>
{% endblock %}

movie_project/templates/edit_profile.html
{% extends 'base.html' %}

{% block content %}
  <h2 style="color: #FF5733; text-align: center;">Edit Profile</h2>
  <form method="post" style="max-width: 400px; margin: 0 auto;">
    {% csrf_token %}
    <div style="margin-bottom: 15px;">
      <label for="id_username" style="display: block; color: #FF5733; font-weight: bold;">Username:</label>
      {{ form.username }}
    </div>
    <div style="margin-bottom: 15px;">
      <label for="id_email" style="display: block; color: #FF5733; font-weight: bold;">Email:</label>
      {{ form.email }}
    </div>
    <div style="margin-bottom: 15px;">
      <label for="id_first_name" style="display: block; color: #FF5733; font-weight: bold;">First Name:</label>
      {{ form.first_name }}
    </div>
    <div style="margin-bottom: 15px;">
      <label for="id_last_name" style="display: block; color: #FF5733; font-weight: bold;">Last Name:</label>
      {{ form.last_name }}
    </div>
    <button type="submit" style="background-color: #FF5733; color: #fff; padding: 10px 20px; border: none; border-radius: 5px; cursor: pointer;">Save Changes</button>
  </form>
{% endblock %}

movie_project/templates/footer.html
<div style="background-color: #ffffff; color: #fff; padding: 20px 0; position:fixed; left: 0; bottom: 0; width: 100%; margin-top: 30px; border-bottom: 2px solid #000000; border-top: 2px solid #000000;">
    <p style="margin: 0; text-align: center; color: black;">&copy; MARVEL</p>
</div>

movie_project/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-color: #ffffff; /* Blue background */
            margin: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        form {
            border: 2px solid #fa0000;; /* Darker blue form background */
            padding: 30px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.5); /* Dark shadow */
            width: 300px;
            max-width: 100%;
            box-sizing: border-box;
        }

        input {
            width: 100%;
            padding: 10px;
            margin-bottom: 20px;
            box-sizing: border-box;
            border: 1px solid #f00303; /* Blue border */
            border-radius: 5px;
            font-size: 16px;
            background-color: #ffffff; /* White background */
            color: #1c4c6d; /* Blue text color */
        }

        input[type="submit"] {
            background-color: #d32e2e; /* Blue background */
            color: #0e0d0d; /* White text color */
            cursor: pointer;
            transition: background-color 0.3s ease;
        }

        input[type="submit"]:hover {
            background-color: #025081; /* Darker blue background on hover */
        }

        label {
            color: #000000; /* Black text color */
        }
    </style>
</head>
<body>
    <div class="messages" style="margin-bottom: 400px; position: absolute; color: #DE3163; font-size:20px">
        {% if messages %}
          {% for message in messages %}
            <div class="{{ message.tags }}" style="margin-bottom: 5px; padding: 10px;">
              {{ message }}
            </div>
          {% endfor %}
        {% endif %}
      </div>
    <form action="{% url 'authentication:login' %}" method="post">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" name="username" required><br><br>

        <label for="password">Password:</label>
        <input type="password" name="password" required><br><br>

        <input type="submit" value="Login">
    </form>
</body>
</html>

movie_project/templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg" style="background-color:#ffffff; font-weight: bolder; border-bottom: 2px solid #000000;">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
   
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item" style="text-align: center;">
                <a href="{% url 'movie_app:allProdCat' %}">
                    <img src="{% static 'image/marvel.png' %}" style="max-height: 100px; max-width: 120px; position: fixed; left: 50%; top: 4%; transform: translate(-50%, -50%);">
                </a>
            </li>
            
            <li class="nav-item d-flex" >
                
                {% if user.is_authenticated %}
                    <span class="nav-link" style="font-variant-caps: all-petite-caps;">Hello {{ user.username }}  <i class="fa-regular fa-face-smile fa-s"></i></span>
                    <a class="nav-link mr-2" style="font-variant-caps: all-petite-caps;" href="{% url 'authentication:logout' %}">logout</a>
                    
                {% else %}
                
                <li class="nav-item d-flex" style="font-variant-caps: all-petite-caps;">
                    <a class="nav-link mr-2 " href="{% url 'authentication:reg' %}">Register</a>
                    <a class="nav-link" href="{% url 'authentication:login' %}">Login</a>
                </li>
                {% endif %}
            </li>
            <li class="nav-item d-flex {% if 'movie_app' in request.path %} active {% endif %}" style="font-variant-caps: all-petite-caps;">
                {% if user.is_authenticated %}
                    <a class="nav-link {% if 'movie_app' in request.path %} active {% endif %}" href="{% url 'movie_app:add_product' %}">Add movie</a>
                    
                {% endif %}
            </li>

        </ul>
        <form class="d-flex" action="{% url 'search_app:SearchResult' %}" method="get">
            {% csrf_token %}
            <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
            <button class="btn" type="submit"><i class="fa-solid fa-magnifying-glass" style="color: #cf5b0e;"></i></button>
        </form>
        
        <li class="nav-item d-flex" style="font-variant-caps: all-petite-caps;">
            {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'movie_app:edit_profile' %}">Edit<i class="fa-regular fa-user"></i></a>
            {% endif %}
        </li>
    </div>
</nav>

<nav class="navbar navbar-expand-lg navbar-light bg-light" style="border-bottom: 2px solid #fd0202;">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mx-auto">
                {% for cat in links %}
                <li class="nav-item" style="font-variant-caps: all-petite-caps; font-weight:600;">
                    <a class="nav-link" href="{{cat.get_url}}">{{cat.name}}</a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <p>
        <button class="btn  mt-2"  data-bs-toggle="collapse" data-bs-target="#collapseWidthExample" aria-expanded="false" aria-controls="collapseWidthExample" style="width: 100px; ">
            <i class="fa-solid fa-message"></i>
        </button> 
      </p>
      <div style="min-height: 5px;">
        <div class="collapse collapse-horizontal" id="collapseWidthExample" >
          <div class="card card-body" style="width: 400px; font-weight: bold;">
            Hai,if you are a marvel fan this website for you
          </div>
        </div>
      </div>
</nav>

movie_project/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {{ product.description|truncatewords:155 }}
{% endblock %}
{% block title %}
    {% if category %}
        {{ product.name }} -  Borcelle
    {% endif %}
{% endblock %}

{% block content %}
<div class="container">
    <div class="row my-4">
        <div class="col-lg-6">
            <img src="{{ product.poster.url }}" alt="{{ product.name }}" class="img-fluid">
        </div>
        <div class="col-lg-6">
            <h1 class="my-4">{{ product.name }}</h1>
            <p class="category">{{ product.category_id }}</p>
            <p class="description">{{ product.description }}</p>
            {% if user == product.user %}
                <div class="admin-actions">
                    <a href="{% url 'movie_app:edit_product' id=product.id %}" class="btn btn-primary">Edit <i class="fa-regular fa-pen-to-square"></i></a>
                    <a href="{% url 'movie_app:delete_product' id=product.id %}" class="btn btn-danger">Delete <i class="fa-solid fa-trash"></i></a>
                </div><BR>
            {% endif %}
            <p><a href="{{ product.trailer_link }}" style="display: inline-block; padding: 10px 20px; background-color: rgb(240, 129, 3); color: #000000; text-decoration: none; border-radius: 5px; border: none; cursor: pointer; transition: background-color 0.3s ease; font-weight: bolder;"><i class="fa-regular fa-circle-play"></i> Watch the Trailer</a></p>
            <p class="average-rating">Average Rating: {{ product.average_rating }}</p>
            <p class="total-ratings">Total Ratings: {{ product.total_ratings }}</p>
            {% if user.is_authenticated %}
                <div class="user-actions">
                    <a href="{% url 'movie_app:add_comment' product_id=product.id %}" class="btn btn-success">Add Comment <i class="fa-regular fa-comment"></i></a>
                    <a href="{% url 'movie_app:add_rating' product_id=product.id %}" class="btn btn-info">Add Rating <i class="fa-regular fa-star"></i></a>
                </div><br>
            {% endif %}
            <h3 class="comments-title">Comments</h3>
            <div class="comments" style="background-color: #e2d9d9; padding: 20px; border-radius: 5px; margin-top: 20px;">
                {% for comment in product.comment_set.all %}
                <div class="comment" style="margin-bottom: 15px; border-bottom: 1px solid #ccc; padding-bottom: 15px;">
                    <p class="text" style="font-size: 16px; color: #333;">{{ comment.text }}</p>
                    <p class="user" style="font-size: 14px; color: #666;">- {{ comment.user.username }} at {{ comment.created_at }}</p>
                </div>
                {% endfor %}
            </div>
            
        </div>
    </div>
</div>
{% endblock %}

movie_project/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registration</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-color: #ffffff; /* Blue background */
            margin: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        form {
            border: 2px solid #ff0000;/* Darker blue form background */
            padding: 30px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.5); /* Dark shadow */
            width: 300px;
            max-width: 100%;
            box-sizing: border-box;
        }

        h2 {
            text-align: center;
            color: #0a0101; /* White text color */
            margin-bottom: 30px;
        }
 
        input {
            width: 100%;
            padding: 10px;
            margin-bottom: 20px;
            box-sizing: border-box;
            border: 1px solid #ff0202; /* Blue border */
            border-radius: 5px;
            font-size: 16px;
            background-color: #ffffff; /* White background */
            color: #1c4c6d; /* Blue text color */
        }

        input[type="submit"] {
            background-color: #db2f2f; /* Blue background */
            color: #0e0d0d; /* White text color */
            cursor: pointer;
            transition: background-color 0.3s ease;
        }

        input[type="submit"]:hover {
            background-color: #025081; /* Darker blue background on hover */
        }

        .login-link {
            text-align: center;
            margin-top: 15px;
        }

        .login-link a {
            color: #ff0909; /* Blue color for the link */
            text-decoration: none;
        }

        .login-link a:hover {
            text-decoration: underline; /* Underline the link on hover */
        }
    </style>
</head>
<body>
    <div class="messages" style="margin-bottom: 700px; position: absolute; color: #ff0000; font-size:20px">
        {% if messages %}
          {% for message in messages %}
            <div class="{{ message.tags }}" style="margin-bottom: 5px; padding: 10px;">
              {{ message }}
            </div>
          {% endfor %}
        {% endif %}
      </div>
<form action="{% url 'authentication:reg' %}" method="post">
    {% csrf_token %}
    <h2>Register</h2>
    <input type="text" name="username" placeholder="Enter your UserName">
    <input type="text" name="first_name" placeholder="Enter your FirstName">
    <input type="text" name="last_name" placeholder="Enter your LastName">
    <input type="email" name="email" placeholder="Enter your Email">
    <input type="password" name="password" placeholder="Enter your Password">
    <input type="password" name="password1" placeholder="Confirm your password">
    <input type="submit" value="Register">
    <div class="login-link">
        <span>Already have an account? </span><a href="{% url 'authentication:login' %}">Login</a>
    </div>
</form>
</body>
</html>

movie_project/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

     we have variety of products.
{% endblock %}
{% block title %}
  search
{% endblock %}
{% block content %}
<div>
    <p class="text-center my_search_text">You have searched for:<b>"{{query}}"</b></p>
</div>
<div class="row mx_auto">
        {% for products in product %}
           <div class="my_bottom_margin col-12 col-sm-6 col-md-4 col-lg-3">
           <div class="card text-center"  style="width: 250px; height: 350px; margin-top: 20px;">
             <a href="{{products.get_url}}"><img class="card-img-top my_image" src="{{products.poster.url}}"  alt="{{products.name}}"></a>
           
           </div>
           </div>

{% empty %}
<div class="row mx-auto">
    <p class="text-center my_search_text"> 0 results found</p>
</div>
{% endfor %}
</div>
{% endblock %}